### ISSUE TITLE
请教大佬，路径找不到！错误代码如下，秋叶大佬的启动器，模型移到了H盘。

### ISSUE THREAD

**Issue by lucknini** [dhs964057117/sd-webui-models-manager#1]
False
H:\sd-models\Stable-diffusion
True
[checkbox, checkbox]
[textbox, textbox]
['Stable-diffusion']
[False, True]
------Stable-diffusion:H:\sd-models\Stable-diffusion
Traceback (most recent call last):
  File "E:\sd-webui-v230315full\python\lib\site-packages\gradio\routes.py", line 422, in run_predict
    output = await app.get_blocks().process_api(
  File "E:\sd-webui-v230315full\python\lib\site-packages\gradio\blocks.py", line 1323, in process_api
    result = await self.call_function(
  File "E:\sd-webui-v230315full\python\lib\site-packages\gradio\blocks.py", line 1051, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "E:\sd-webui-v230315full\python\lib\site-packages\anyio\to_thread.py", line 31, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "E:\sd-webui-v230315full\python\lib\site-packages\anyio\_backends\_asyncio.py", line 937, in run_sync_in_worker_thread
    return await future
  File "E:\sd-webui-v230315full\python\lib\site-packages\anyio\_backends\_asyncio.py", line 867, in run
    result = context.run(func, *args)
  File "E:\sd-webui-v230315full\extensions\sd-webui-models-manager\scripts\main.py", line 109, in create_symbol_link
    create_symbolic_links(selectPath[i],os.path.join(paths.models_path, selectKey[i]))
  File "E:\sd-webui-v230315full\extensions\sd-webui-models-manager\scripts\main.py", line 91, in create_symbolic_links
    os.symlink(source_path, target_path)
OSError: [WinError 1314] 客户端没有所需的特权。: 'H:\\sd-models\\Stable-diffusion\\768-v-ema.civitai.info' -> 'E:\\sd-webui-v230315full\\models\\Stable-diffusion\\768-v-ema.civitai.info'
提示：Python 运行时抛出了一个异常。请检查疑难解答页面。

**Comment by dhs964057117** [comment]
管理员身份运行启动器，然后重新输入地址配置一下就可以了

**Comment by lucknini** [comment]
谢谢大佬，搞定了！
